### ISSUE TITLE
[v1.0] MEGA testing and debug campaign

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/FYP#15]
## About
This is a task tracking of all new functions that needed to debug and testing.
## Tasks
- [x] Bait swap
- [x] Fish throw back
- [x] Trash spawning
- [x] Trash Grabbing
- [x] Player data saving and reading
- [x] Shop UI
- [ ] Buying item from shop
- [ ] Spawn unlocked and selected bait
- [x] Adding fish to inventory
- [x] Selling item from shop
- [ ] Selling all items from shop
- [x] Fish catch comparison mechanic
- [x] Reel handle physics
- [x] Go back to menu
##

**Comment by ChisanaKita** [comment]
Bye
