### ISSUE TITLE
[Mega-Thread] Documentations - Project Initial Report

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/FYP#2]
Deadline : 13 Nov 2020 (As version 0.1)

#### TODO List
- [x] Create report file (@ChisanaKita)
- [x] Draft report structure
- [x] Abstract
- [x] Introduction
  - [x] State the goals of the game
  - [x] Document Structure
- [x] Game Design 
  - [x] List of the basic constraints and requirements
  - [x] Design Thinking 
- [x] Game Overview
  - [x] Story background
  - [x] Play modes
  - [x] System Architecture 
- [x] Game World
  - [x] Game Environment
  - [x] Level Design
  - [x] Maps Design
  - [x] Characters
- [x] Objects 
- [x] Gameplay Description
  - [x] User Interface Design
  - [x] Control
---
- ~Software Design~    (Optional)
  - ~Use Case Diagram~
  - ~Class Diagrams~
  - ~Sequence Diagrams~
---
- [x] Hardware and Software Requirements
- [x] Technical Considerations
- [x] Project Plan
  - [x] Schedule
  - [x] Milestone description
  - [x] Action Plan
- [x] References
- [x] Appendices
  - [x] Workload Distribution
  - [x] Budget Estimation
  - [x] Log Sheets
- [x] QA
  - [x] Final check by : @ChisanaKita 
  - [x] Supervisor feed back
  - [x] fixes (If any)

**Comment by Leong15** [comment]
![fishContainer_front](https://user-images.githubusercontent.com/53085228/97898044-4a012b80-1d72-11eb-8184-0715acd9bdf0.jpg)
![fishContainer_top](https://user-images.githubusercontent.com/53085228/97898053-4cfc1c00-1d72-11eb-8df0-8615e6d05a0c.jpg)
![fishBait](https://user-images.githubusercontent.com/53085228/97900167-46bb6f00-1d75-11eb-95d4-6fef90cac8f4.jpg)
image for object

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97956808-9c7b3000-1de4-11eb-8ebe-02353619045c.png)

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97958801-f1b94080-1de8-11eb-8874-864aa02e73b4.png)

**Comment by Leong15** [comment]
![Uploading image.png…]()

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97959198-c5ea8a80-1de9-11eb-9424-5b211b272701.png)

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97959695-de0ed980-1dea-11eb-9327-dfc3cbc231d4.png)

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97960356-47dbb300-1dec-11eb-89a0-aee51873e91c.png)

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97961006-6ee6b480-1ded-11eb-9516-82f6034187b8.png)
