### ISSUE TITLE
[v0.5] Unity Script - Player

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/FYP#9]
## About
This is a task tracking of the player. If all boxes are checked, that means this task is completed.
## Tasks
- [x] Implement SteamVR into Unity
- [x] Set up my VIVE
- [x] Binding control scheme
- [x] Implement control
  - [x] Grabbing Object
  - [x] Interacting Object
- [x] Testing
##

**Comment by ChisanaKita** [comment]
Yup
